# .github/workflows/sync-notes.yml
name: Sync Notes and Deploy

on:
  repository_dispatch:
    types: [sync-notes]


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Pull latest notes
        run: |
          git clone https://github.com/aslamcodes/brain-cache notes
          rsync -av --exclude='.git' --exclude='.obsidian' notes/ ./content

      - name: Commit & Push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Update notes"
          git pull --rebase origin main
          git push origin main

