# .github/workflows/sync-notes.yml
name: Sync Notes and Deploy

on:
  repository_dispatch:
    types: [sync-notes]


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          ref: main  

      - name: Empty Commit
        run: |
          git commit --allow-empty -m "Empty Trigger"
          git pull origin main --rebase
          git push origin main
